// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBtG1XfrnK3Mkb1h2rfyCANC5PtmuFjnM',
    appId: '1:595552764849:web:a7f16cbf75596db15a3390',
    messagingSenderId: '595552764849',
    projectId: 'saloon-2a65c',
    authDomain: 'saloon-2a65c.firebaseapp.com',
    storageBucket: 'saloon-2a65c.appspot.com',
    measurementId: 'G-MJ4KD4YFQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYRXpgpuh1EIBbI3ZsFqDV_QSwzGb3TB8',
    appId: '1:595552764849:android:cee0b60d854eb9a75a3390',
    messagingSenderId: '595552764849',
    projectId: 'saloon-2a65c',
    storageBucket: 'saloon-2a65c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjVU-Ge69agBzpOi2O634eLjaRU9rAyJs',
    appId: '1:595552764849:ios:34145d6c8ebbd3a75a3390',
    messagingSenderId: '595552764849',
    projectId: 'saloon-2a65c',
    storageBucket: 'saloon-2a65c.appspot.com',
    iosBundleId: 'com.example.bwiAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjVU-Ge69agBzpOi2O634eLjaRU9rAyJs',
    appId: '1:595552764849:ios:5d7a99690b6c97fd5a3390',
    messagingSenderId: '595552764849',
    projectId: 'saloon-2a65c',
    storageBucket: 'saloon-2a65c.appspot.com',
    iosBundleId: 'com.example.bwiAssignment.RunnerTests',
  );
}
